name: bab_alomda_assessment_flutter
description: Bab Alomda assessment project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  retrofit: ^4.0.3
  dio: ^5.3.3
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  animations: ^2.0.8
  google_fonts: ^6.1.0
  flutter_bloc: ^8.1.3
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.3
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true